cbs/urls.py
from rest_framework.routers import DefaultRouter
from . import views
from django.urls import path


app_name = "cbs"

router = DefaultRouter()

router.register("bank-accounts", views.BankAccountViewset, basename="bank-accounts")
router.register("transfer", views.TransferViewset, basename="transfer")
router.register("payment-billers", views.PaymentBiller, basename="payment-billers")
router.register("payments", views.PaymentViewset, basename="payments")
router.register("bank-statement", views.BankStatementViewset, basename="bank-statement")
router.register("beneficiary", views.BeneficiaryViewset, basename="beneficiary")
router.register("standing-order", views.StandingOrderViewset, basename="standing-order")
router.register("cheque-request", views.ChequeRequestViewset, basename="cheque-request")
router.register(
    "loan-categories", views.LoanCategoryViewset, basename="loan-categories"
)
router.register("loan-requests", views.LoanRequestViewset, basename="loan-requests")
router.register(
    "appointment-booking",
    views.AppointmentBookingViewset,
    basename="appointment-booking",
)
router.register("expense-limit", views.ExpenseLimitViewset, basename="expense-limit")
router.register(
    "cardless-withdrawal",
    views.CardlessWithdrawalViewset,
    basename="cardless-withdrawal",
)
router.register(
    "email-indemnity", views.EmailIndemnityViewset, basename="email-indemnity"
)
router.register("bill-sharing", views.BillSharingViewset, basename="bill-sharing")
router.register(
    "bill-sharing-payee", views.BillSharingPayeeViewset, basename="bill-sharing-payee"
)
router.register("cards", views.CardViewset, basename="cards")
router.register("card-requests", views.CardRequestViewset, basename="card-requests")
router.register(
    "card-management", views.CardManagementViewset, basename="card-management"
)
router.register("travel-notice", views.TravelNoticeViewset, basename="travel-notice")
router.register("complaints", views.ComplaintViewset, basename="complaints")
router.register(
    "complaint-category",
    views.ComplaintCategoryViewset,
    basename="complaint-category",
)
router.register("service-charges", views.BankChargesViewset, basename="service-charges")
urlpatterns = [
    path(
        "fx-rates/",
        views.ForexViewset.as_view(),
        name="fx-rates",
    ),
]

urlpatterns += router.urls

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)
from django.views.i18n import set_language

urlpatterns = [
    path("digital/control/", admin.site.urls),
    path("i18n/", set_language, name="set_language"),
    path("accounts/", include("allauth.urls")),
    path("", include("dashboard.urls")),
    path("ocr/", include("ocr.urls")),
    path("datatables/", include("datatable.urls")),
    path("cbs/", include("cbs.urls")),
    path("auth/", include("accounts.urls")),
    path("chatbot/", include("chatbot.urls")),
    path("digital/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "digital/api-docs/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "digital/api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
]

urlpatterns = (
    urlpatterns
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"
urlpatterns = [
    path("", views.staff_login, name="loginview"),
    path("verify-account/", views.verify_otp_view, name="verify-2fa-otp"),
    path("dashboard/", views.index, name="dashboard"),
    #  URLS FOR CUSTOMERS
    path("customers/", views.customers, name="customers"),
    path(
        "customers/<uuid:uuid>/detail/",
        views.customer_detail,
        name="customer-detail",
    ),
    path(
        "password/<uuid:uuid>/reset-password/",
        views.customer_password_reest,
        name="customer-reset-password",
    ),
    path(
        "password/<uuid:uuid>/send-temporary/",
        views.send_temporary_password,
        name="send-temporary-password",
    ),
    path(
        "password-reset/<uuid:uuid>/",
        views.send_password_reset_link,
        name="send-password-reset-link",
    ),
    path(
        "customers/<uuid:uuid>/deactivate-account/",
        views.deactivate_customer_account,
        name="customer-account-deactivation",
    ),
    path(
        "pin-reset/<uuid:uuid>/",
        views.customer_pin_reest,
        name="customer-reset-pin",
    ),
    path(
        "pin-reset/<uuid:uuid>/send-link/",
        views.send_pin_reset_link,
        name="send-pin-reset-link",
    ),
    path(
        "customers/<uuid:uuid>/activate-account/",
        views.activate_customer_account,
        name="customer-account-activation",
    ),
    # CUSTOMER REQUESTS
    path("customer-requests/", views.customer_requests, name="customer-requests"),
    path(
        "customer-requests/bank-statements/",
        views.bank_statement,
        name="bank-statements",
    ),
    path(
        "customer-requests/bank-statements/hisotry/",
        views.bank_statement_hisotry,
        name="bank-statements-history",
    ),
    path(
        "customer-requests/bank-statements/<uuid:uuid>/detail/",
        views.bank_statement_detail,
        name="bank-statements-detail",
    ),
    # TRANSFERS
    path(
        "transactions/transfers/",
        views.transfers,
        name="transfers",
    ),
    path(
        "customer-requests/transfers/<uuid:uuid>/detail/",
        views.transfer_requests_detail,
        name="transfer-requests-detail",
    ),
    path(
        "customer-requests/transfers/history/",
        views.transfer_requests_history,
        name="transfer-requests-hisotry",
    ),
    # CHEQUE REQUESTS
    path(
        "customer-requests/cheque/",
        views.cheque_requests,
        name="cheque-requests",
    ),
    path(
        "customer-requests/cheque/<uuid:uuid>/detail/",
        views.cheque_request_detail,
        name="cheque-requests-detail",
    ),
    path(
        "customer-requests/cheque/history/",
        views.cheque_request_history,
        name="cheque-requests-history",
    ),
    # CHEQUE REQUESTS
    path(
        "customer-requests/card-services/",
        views.card_request,
        name="card-requests",
    ),
    path(
        "customer-requests/card-services/<uuid:uuid>/detail/",
        views.card_request_detail,
        name="card-requests-detail",
    ),
    path(
        "customer-requests/card-services/history/",
        views.card_request_history,
        name="card-requests-history",
    ),
    # LOAN REQUESTS
    path(
        "customer-requests/loan-requests/",
        views.loan_requests,
        name="loan-requests",
    ),
    path(
        "customer-requests/loan-requests/history/",
        views.loan_requests_history,
        name="loan-requests-history",
    ),
    path(
        "customer-requests/loan-requests/<uuid:uuid>/detail/",
        views.loan_request_detail,
        name="loan-requests-detail",
    ),
    # PAYMENT
    path("payments/", views.payments, name="payments"),
    path(
        "payments/<uuid:uuid>/detail/",
        views.payments_detail,
        name="payment-detail",
    ),
    # ONBOARDING URLS
    path(
        "onboarding/new-customer/verify-phone/",
        views.verify_phone_number,
        name="onboarding-verify-phone",
    ),
    path(
        "onboarding/new-customer/verify-email/",
        views.verify_email,
        name="onboarding-verify-email",
    ),
    path(
        "onboarding/new-customer/complete-kyc/",
        views.customer_onboarding_kyc,
        name="onboarding-new-customer-kyc",
    ),
]

dashboard/models.py
# from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from datatable import models as datatables
from cbs import models as cbsmodel
from accounts.models import CustomUser
from django import forms
from phonenumber_field.formfields import PhoneNumberField
from django.core.exceptions import ValidationError


class AddQuestionForm(forms.ModelForm):
    class Meta:
        model = datatables.SecurityQuestion
        fields = ["question"]


class AddTransactionPurposeForm(forms.ModelForm):
    class Meta:
        model = datatables.TransactionPurpose
        fields = ["name"]


class AddOccupationForm(forms.ModelForm):
    class Meta:
        model = datatables.Occupation
        fields = ["name"]


class AddBankBranchForm(forms.ModelForm):
    class Meta:
        model = datatables.BankBranch
        fields = (
            "name",
            "country",
            "langtitude_cordinates",
            "longitude_cordinates",
            "address",
            "closed",
        )


class AddAtmLocation(forms.ModelForm):
    class Meta:
        model = datatables.Atm
        fields = (
            "country",
            "langtitude_cordinates",
            "longitude_cordinates",
            "address",
        )


class AccountDeactivationForm(forms.Form):
    reason = forms.CharField(max_length=255, widget=forms.Textarea())
    password = forms.CharField(max_length=255, widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super(AccountDeactivationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            visible.field.required = True


class CustomerPasswordResetForm(forms.Form):
    pin = forms.CharField(max_length=100)
    new_password = forms.CharField(max_length=255, widget=forms.PasswordInput())


class CustomerPINResetForm(forms.Form):
    password = forms.CharField(max_length=100, widget=forms.PasswordInput())
    new_pin = forms.CharField(max_length=100, widget=forms.PasswordInput())


class EditTransferForm(forms.ModelForm):
    class Meta:
        model = cbsmodel.Transfer
        fields = (
            "status",
            "t24_reference",
        )


class CorporateUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = (
            "first_name",
            "last_name",
            "phone_number",
            "email",
        )


class ChangeBankStatementStatus(forms.ModelForm):
    class Meta:
        model = cbsmodel.BankStatement
        fields = ("status", "comments")

    def __init__(self, *args, **kwargs):
        super(ChangeBankStatementStatus, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            visible.field.required = True


class ChangeLoanrequestStatus(forms.ModelForm):
    class Meta:
        model = cbsmodel.LoanRequest
        fields = ("application_id", "status", "comments")

    def __init__(self, *args, **kwargs):
        super(ChangeLoanrequestStatus, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            if visible.name != "application_id":
                visible.field.required = True


class ChangeTransferRequestStatus(forms.ModelForm):
    class Meta:
        model = cbsmodel.Transfer
        fields = ("t24_reference", "status", "failed_reason")

    def __init__(self, *args, **kwargs):
        super(ChangeTransferRequestStatus, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            if visible.name != "t24_reference" and visible.name != "failed_reason":
                visible.field.required = True


class ChequeRequestStatusChange(forms.ModelForm):
    class Meta:
        model = cbsmodel.ChequeRequest
        fields = ("status", "comments")

    def __init__(self, *args, **kwargs):
        super(ChequeRequestStatusChange, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            visible.field.required = True


class CardRequestStatusChange(forms.ModelForm):
    class Meta:
        model = cbsmodel.CardRequest
        fields = ("status", "comments")

    def __init__(self, *args, **kwargs):
        super(CardRequestStatusChange, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            visible.field.required = True


class NewCustomerVerifyPhoneForm(forms.Form):
    phone_number = PhoneNumberField()


class NewCustomerVerifyEmailForm(forms.Form):
    email = forms.EmailField(label="Email")


class SignUpNewCustomerForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    nationality = forms.CharField()
    gender = forms.CharField()
    date_of_birth = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))
    profile_picture = forms.ImageField()
    id_front = forms.ImageField()
    id_back = forms.ImageField(required=False)
    id_number = forms.CharField()
    date_of_issuance = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))
    date_of_expiry = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))
    place_of_issuance = forms.CharField()

    def clean_security_questions(self):
        data = self.cleaned_data.get("security_questions")
        # Optionally, add custom validation for the structure of each question-answer pair
        # e.g. ensure it's a list of dicts with keys: "question", "answer"
        if data:
            if not isinstance(data, list):
                raise ValidationError("Security questions must be a list.")
            for item in data:
                if not isinstance(item, dict):
                    raise ValidationError(
                        "Each security question must be a dictionary."
                    )
                if "question" not in item or "answer" not in item:
                    raise ValidationError(
                        "Each security question must have 'question' and 'answer'."
                    )
        return data

dashboard/templates/customer_request/card_services/card_service_requests.html
{% extends 'core_base.html' %} {% block content %}

<div class="card">
  <div class="card-header bg-header d-flex justify-content-between">
    <h4 class="card-title">Card Requests</h4>
    <a href="{% url 'dashboard:cheque-requests-history' %}" class="btn btn-primary btn-sm">View History</a>
  </div>
  <div class="card-body">
    <div
      id="basic-datatables_wrapper"
      class="dataTables_wrapper container-fluid dt-bootstrap4"
    >

      <div class="table-responsive">
        <div class="col-sm-12">
          <table  class="table table-striped table-hover dataTable">
            <thead>
              <tr>
                <th>#</th>
                <th>Customer ID</th>
                <th>Customer Name</th>
                <th>Source Account</th>
                <th>Card Type</th>
                <th>Status</th>
                <th>Date</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {% for card_request in card_requests %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td class="text-align-left">
                  <a href="{% url 'dashboard:customer-detail' card_request.user.customer_profile.uuid %}">
                    {{ card_request.user.customer_profile.t24_customer_id }}
                  </a>
                </td>
                <td>{{ card_request.user.fullname }}</td>

                <td>{{ card_request.source_account.account_number }}</td>
                <td>{{ card_request.card_type }}</td>
                <td>
                  {% with status=card_request.status %}
                      {% include 'components/loan_status.html' %}
                  {% endwith %}
                </td>

                <td>{{ card_request.date_created }}</td>
                <td>
                  <a href="{% url 'dashboard:card-requests-detail' card_request.uuid %}">View</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

dashboard/templates/customer_request/card_services/card_service_requests_detail.html
{% extends 'core_base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<section class="row">
  <div class="col-md-6">
    <div class="card">
      <div
        class="card-header text-center align-items-center justify-content-center {% if card_request.status == 'PENDING' %} bg-light-warning {% elif card_request.status == 'REJECTED' %} bg-light-danger {% elif card_request.status == 'FAILED' %} bg-light-danger {% elif card_request.status == 'COMPLETED' %}bg-light-success{% elif card_request.status == 'PROCESSING' %}bg-light-primary {% endif %}"
      >
        <h6>{{ card_request.status }}</h6>
        <h2 class="pt-1">{{ card_request.card_service_type }}</h2>
        <small class="text-muted">{{ card_request.date_created }}</small>
      </div>

      <div class="card-body pt-4">
        <!-- Customer Information Section -->
        <div class="row">
          <div class="col-md-12">
            <small class="text-muted">CUSTOMER INFORMATION</small>
          </div>
        </div>
        <div class="row pt-2">
          <div class="col-md-4">
            <div class="form-group">
              <label for="disabledInput">Customer ID</label>
              <p class="form-control-static">
                {{ card_request.user.customer_profile.t24_customer_id }}
              </p>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <label for="disabledInput">Customer Name</label>
              <p class="form-control-static">
                {{ card_request.user.fullname }}
              </p>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <label for="disabledInput">Phone Number</label>
              <p class="form-control-static">
                {{ card_request.user.phone_number }}
              </p>
            </div>
          </div>
        </div>
        <hr />

        <!-- Account Information Section -->
        <div class="row">
          <div class="col-md-12">
            <small class="text-muted">ACCOUNT INFORMATION</small>
          </div>
        </div>
        <div class="row pt-3">
          <div class="col-md-6">
            <div class="form-group">
              <label for="disabledInput">Account #</label>
              <p class="form-control-static">
                {{ card_request.source_account.account_number }}
              </p>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="disabledInput">Product Type</label>
              <p class="form-control-static">{{ card_request.source_account.product_type|default:"Current Account" }}</p>
            </div>
          </div>
          {% if card_request.request_debit_account %}
          <div class="col-md-6">
            <div class="form-group">
              <label for="disabledInput">Debit Account</label>
              <p class="form-control-static">
                {{ card_request.request_debit_account }}
              </p>
            </div>
          </div>
          {% endif %}
        </div>
        <hr />

        <!-- Card Service Details Section -->
        <div class="row">
          <div class="col-md-12">
            <small class="text-muted">CARD SERVICE DETAILS</small>
          </div>
        </div>
        <div class="row pt-3">
          <div class="col-md-6">
            <div class="form-group">
              <label for="disabledInput">Request Type</label>
              <p class="form-control-static">
                {{ card_request.card_service_type }}
              </p>
            </div>
          </div>

          {% if card_request.card_type %}
          <div class="col-md-6">
            <div class="form-group">
              <label for="disabledInput">Card Type</label>
              <p class="form-control-static">
                {{ card_request.card_type }}
              </p>
            </div>
          </div>
          {% endif %}

          {% if card_request.card_number %}
          <div class="col-md-6">
            <div class="form-group">
              <label for="disabledInput">Card Number</label>
              <p class="form-control-static">
                {{ card_request.card_number }}
              </p>
            </div>
          </div>
          {% endif %}


          <!-- Delivery Information Section -->
          <div class="col-md-6">
            <div class="form-group">
              <label for="disabledInput">Delivery Address</label>
              <p class="form-control-static">
                {{ card_request.address }}
              </p>
            </div>
          </div>

          <div class="col-md-6">
            <div class="form-group">
              <label for="disabledInput">Pick-Up Branch</label>
              <p class="form-control-static">
                {{ card_request.branch.name }}
              </p>
            </div>
          </div>

          {% if card_request.reason %}
          <div class="col-md-12">
            <div class="form-group">
              <label for="disabledInput">Reason</label>
              <p class="form-control-static">
                {{ card_request.reason }}
              </p>
            </div>
          </div>
          {% endif %}
        </div>



        {% if card_request.comments %}
        <div class="row pt-3">
          <div class="col-md-12">
            <div class="form-group">
              <label for="disabledInput">Comments</label>
              <p class="form-control-static">
                {{ card_request.comments }}
              </p>
            </div>
          </div>
        </div>
        {% endif %}
        <hr />

        <!-- Status Information Section -->
        <div class="row">
          <div class="col-md-12">
            <small class="text-muted">STATUS INFORMATION</small>
          </div>
        </div>
        <div class="row pt-3">

          <div class="col-md-6">
            <div class="form-group">
              <label for="disabledInput">Date Created</label>
              <p class="form-control-static">
                {{ card_request.date_created }}
              </p>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="disabledInput">Last Updated</label>
              <p class="form-control-static">{{ card_request.last_updated }}</p>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>

  <div class="col-md-6 text-right">

    <div class="card">
        <div class="card-body">
            <h5>Notify Customer</h5>
            {% if  card_request.status == 'PENDING'  or card_request.status == 'PROCESSING' %}

            <form method="post" class="mt-4">
                {% csrf_token %}
                {{ change_status_form | crispy }}
              <div>
                <input type="submit" class="btn btn-md btn-success" value="Notify Customer">
              </div>
            </form>
            <br>

            {% else %}
            <p>Customer has already been notified</p>
            <br>
            <h6>Comments</h6>
            <p>{{ card_request.comments }}</p>
            {% endif %}
            <br>

        </div>
    </div>

  </div>
</section>
{% endblock %}

dashboard/templates/customer_request/card_services/card_service_requests_history.html
{% extends 'core_base.html' %} {% block content %}

<div class="card">
  <div class="card-header bg-header">
    <h4 class="card-title">Cheque Request History</h4>
  </div>
  <div class="card-body">
    <div
      id="basic-datatables_wrapper"
      class="dataTables_wrapper container-fluid dt-bootstrap4"
    >
      <div class="col-md-12">

      </div>

      <div class="table-responsive">
        <div class="col-sm-12">
          <table  class="table table-striped table-hover dataTable">
            <thead>
              <tr>
                <th>#</th>
                <th>Customer ID</th>
                <th>Customer Name</th>
                <th>Source Account</th>
                <th>Request Type</th>
                <th>Status</th>
                <th>Date</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {% for card_request in card_requests %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td class="text-align-left">
                  <a href="{% url 'dashboard:customer-detail' card_request.user.uuid %}">
                    {{ card_request.user.customer_profile.t24_customer_id }}
                  </a>
                </td>
                <td>{{ card_request.user.fullname }}</td>

                <td>{{ card_request.source_account.account_number }}</td>
                <td>{{ card_request.card_service_type }}</td>
                <td>
                  {% with status=card_request.status %}
                      {% include 'components/loan_status.html' %}
                  {% endwith %}
                </td>

                <td>{{ card_request.date_created }}</td>
                <td>
                  <a href="{% url 'dashboard:cheque-requests-detail' card_request.uuid %}">View</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}