cbs/urls.py
from rest_framework.routers import DefaultRouter
from . import views
from django.urls import path


app_name = "cbs"

router = DefaultRouter()

router.register("bank-accounts", views.BankAccountViewset, basename="bank-accounts")
router.register("transfer", views.TransferViewset, basename="transfer")
router.register("payment-billers", views.PaymentBiller, basename="payment-billers")
router.register("payments", views.PaymentViewset, basename="payments")
router.register("bank-statement", views.BankStatementViewset, basename="bank-statement")
router.register("beneficiary", views.BeneficiaryViewset, basename="beneficiary")
router.register("standing-order", views.StandingOrderViewset, basename="standing-order")
router.register("cheque-request", views.ChequeRequestViewset, basename="cheque-request")
router.register(
    "loan-categories", views.LoanCategoryViewset, basename="loan-categories"
)
router.register("loan-requests", views.LoanRequestViewset, basename="loan-requests")
router.register(
    "appointment-booking",
    views.AppointmentBookingViewset,
    basename="appointment-booking",
)
router.register("expense-limit", views.ExpenseLimitViewset, basename="expense-limit")
router.register(
    "cardless-withdrawal",
    views.CardlessWithdrawalViewset,
    basename="cardless-withdrawal",
)
router.register(
    "email-indemnity", views.EmailIndemnityViewset, basename="email-indemnity"
)
router.register("bill-sharing", views.BillSharingViewset, basename="bill-sharing")
router.register(
    "bill-sharing-payee", views.BillSharingPayeeViewset, basename="bill-sharing-payee"
)
router.register("cards", views.CardViewset, basename="cards")
router.register("card-requests", views.CardRequestViewset, basename="card-requests")
router.register(
    "card-management", views.CardManagementViewset, basename="card-management"
)
router.register("travel-notice", views.TravelNoticeViewset, basename="travel-notice")
router.register("complaints", views.ComplaintViewset, basename="complaints")
router.register(
    "complaint-category",
    views.ComplaintCategoryViewset,
    basename="complaint-category",
)
router.register("service-charges", views.BankChargesViewset, basename="service-charges")
urlpatterns = [
    path(
        "fx-rates/",
        views.ForexViewset.as_view(),
        name="fx-rates",
    ),
]

urlpatterns += router.urls

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)
from django.views.i18n import set_language

urlpatterns = [
    path("digital/control/", admin.site.urls),
    path("i18n/", set_language, name="set_language"),
    path("accounts/", include("allauth.urls")),
    path("", include("dashboard.urls")),
    path("ocr/", include("ocr.urls")),
    path("datatables/", include("datatable.urls")),
    path("cbs/", include("cbs.urls")),
    path("auth/", include("accounts.urls")),
    path("chatbot/", include("chatbot.urls")),
    path("digital/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "digital/api-docs/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "digital/api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
]

urlpatterns = (
    urlpatterns
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"
urlpatterns = [
    path("", views.staff_login, name="loginview"),
    path("verify-account/", views.verify_otp_view, name="verify-2fa-otp"),
    path("dashboard/", views.index, name="dashboard"),
    #  URLS FOR CUSTOMERS
    path("customers/", views.customers, name="customers"),
    path(
        "customers/<uuid:uuid>/detail/",
        views.customer_detail,
        name="customer-detail",
    ),
    path(
        "password/<uuid:uuid>/reset-password/",
        views.customer_password_reest,
        name="customer-reset-password",
    ),
    path(
        "password/<uuid:uuid>/send-temporary/",
        views.send_temporary_password,
        name="send-temporary-password",
    ),
    path(
        "password-reset/<uuid:uuid>/",
        views.send_password_reset_link,
        name="send-password-reset-link",
    ),
    path(
        "customers/<uuid:uuid>/deactivate-account/",
        views.deactivate_customer_account,
        name="customer-account-deactivation",
    ),
    path(
        "pin-reset/<uuid:uuid>/",
        views.customer_pin_reest,
        name="customer-reset-pin",
    ),
    path(
        "pin-reset/<uuid:uuid>/send-link/",
        views.send_pin_reset_link,
        name="send-pin-reset-link",
    ),
    path(
        "customers/<uuid:uuid>/activate-account/",
        views.activate_customer_account,
        name="customer-account-activation",
    ),
    # CUSTOMER REQUESTS
    path("customer-requests/", views.customer_requests, name="customer-requests"),
    path(
        "customer-requests/bank-statements/",
        views.bank_statement,
        name="bank-statements",
    ),
    path(
        "customer-requests/bank-statements/hisotry/",
        views.bank_statement_hisotry,
        name="bank-statements-history",
    ),
    path(
        "customer-requests/bank-statements/<uuid:uuid>/detail/",
        views.bank_statement_detail,
        name="bank-statements-detail",
    ),
    # TRANSFERS
    path(
        "transactions/transfers/",
        views.transfers,
        name="transfers",
    ),
    path(
        "customer-requests/transfers/<uuid:uuid>/detail/",
        views.transfer_requests_detail,
        name="transfer-requests-detail",
    ),
    path(
        "customer-requests/transfers/history/",
        views.transfer_requests_history,
        name="transfer-requests-hisotry",
    ),
    # CHEQUE REQUESTS
    path(
        "customer-requests/cheque/",
        views.cheque_requests,
        name="cheque-requests",
    ),
    path(
        "customer-requests/cheque/<uuid:uuid>/detail/",
        views.cheque_request_detail,
        name="cheque-requests-detail",
    ),
    path(
        "customer-requests/cheque/history/",
        views.cheque_request_history,
        name="cheque-requests-history",
    ),
    # CHEQUE REQUESTS
    path(
        "customer-requests/card-services/",
        views.card_request,
        name="card-requests",
    ),
    path(
        "customer-requests/card-services/<uuid:uuid>/detail/",
        views.card_request_detail,
        name="card-requests-detail",
    ),
    path(
        "customer-requests/card-services/history/",
        views.card_request_history,
        name="card-requests-history",
    ),
    # LOAN REQUESTS
    path(
        "customer-requests/loan-requests/",
        views.loan_requests,
        name="loan-requests",
    ),
    path(
        "customer-requests/loan-requests/history/",
        views.loan_requests_history,
        name="loan-requests-history",
    ),
    path(
        "customer-requests/loan-requests/<uuid:uuid>/detail/",
        views.loan_request_detail,
        name="loan-requests-detail",
    ),
    # PAYMENT
    path("payments/", views.payments, name="payments"),
    path(
        "payments/<uuid:uuid>/detail/",
        views.payments_detail,
        name="payment-detail",
    ),
    # ONBOARDING URLS
    path(
        "onboarding/new-customer/verify-phone/",
        views.verify_phone_number,
        name="onboarding-verify-phone",
    ),
    path(
        "onboarding/new-customer/verify-email/",
        views.verify_email,
        name="onboarding-verify-email",
    ),
    path(
        "onboarding/new-customer/complete-kyc/",
        views.customer_onboarding_kyc,
        name="onboarding-new-customer-kyc",
    ),
]

dashboard/models.py
# from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from datatable import models as datatables
from cbs import models as cbsmodel
from accounts.models import CustomUser
from django import forms
from phonenumber_field.formfields import PhoneNumberField
from django.core.exceptions import ValidationError


class AddQuestionForm(forms.ModelForm):
    class Meta:
        model = datatables.SecurityQuestion
        fields = ["question"]


class AddTransactionPurposeForm(forms.ModelForm):
    class Meta:
        model = datatables.TransactionPurpose
        fields = ["name"]


class AddOccupationForm(forms.ModelForm):
    class Meta:
        model = datatables.Occupation
        fields = ["name"]


class AddBankBranchForm(forms.ModelForm):
    class Meta:
        model = datatables.BankBranch
        fields = (
            "name",
            "country",
            "langtitude_cordinates",
            "longitude_cordinates",
            "address",
            "closed",
        )


class AddAtmLocation(forms.ModelForm):
    class Meta:
        model = datatables.Atm
        fields = (
            "country",
            "langtitude_cordinates",
            "longitude_cordinates",
            "address",
        )


class AccountDeactivationForm(forms.Form):
    reason = forms.CharField(max_length=255, widget=forms.Textarea())
    password = forms.CharField(max_length=255, widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super(AccountDeactivationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            visible.field.required = True


class CustomerPasswordResetForm(forms.Form):
    pin = forms.CharField(max_length=100)
    new_password = forms.CharField(max_length=255, widget=forms.PasswordInput())


class CustomerPINResetForm(forms.Form):
    password = forms.CharField(max_length=100, widget=forms.PasswordInput())
    new_pin = forms.CharField(max_length=100, widget=forms.PasswordInput())


class EditTransferForm(forms.ModelForm):
    class Meta:
        model = cbsmodel.Transfer
        fields = (
            "status",
            "t24_reference",
        )


class CorporateUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = (
            "first_name",
            "last_name",
            "phone_number",
            "email",
        )


class ChangeBankStatementStatus(forms.ModelForm):
    class Meta:
        model = cbsmodel.BankStatement
        fields = ("status", "comments")

    def __init__(self, *args, **kwargs):
        super(ChangeBankStatementStatus, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            visible.field.required = True


class ChangeLoanrequestStatus(forms.ModelForm):
    class Meta:
        model = cbsmodel.LoanRequest
        fields = ("application_id", "status", "comments")

    def __init__(self, *args, **kwargs):
        super(ChangeLoanrequestStatus, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            if visible.name != "application_id":
                visible.field.required = True


class ChangeTransferRequestStatus(forms.ModelForm):
    class Meta:
        model = cbsmodel.Transfer
        fields = ("t24_reference", "status", "failed_reason")

    def __init__(self, *args, **kwargs):
        super(ChangeTransferRequestStatus, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            if visible.name != "t24_reference" and visible.name != "failed_reason":
                visible.field.required = True


class ChequeRequestStatusChange(forms.ModelForm):
    class Meta:
        model = cbsmodel.ChequeRequest
        fields = ("status", "comments")

    def __init__(self, *args, **kwargs):
        super(ChequeRequestStatusChange, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            visible.field.required = True


class CardRequestStatusChange(forms.ModelForm):
    class Meta:
        model = cbsmodel.CardRequest
        fields = ("status", "comments")

    def __init__(self, *args, **kwargs):
        super(CardRequestStatusChange, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            visible.field.required = True


class NewCustomerVerifyPhoneForm(forms.Form):
    phone_number = PhoneNumberField()


class NewCustomerVerifyEmailForm(forms.Form):
    email = forms.EmailField(label="Email")


class SignUpNewCustomerForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    nationality = forms.CharField()
    gender = forms.CharField()
    date_of_birth = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))
    profile_picture = forms.ImageField()
    id_front = forms.ImageField()
    id_back = forms.ImageField(required=False)
    id_number = forms.CharField()
    date_of_issuance = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))
    date_of_expiry = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))
    place_of_issuance = forms.CharField()

    def clean_security_questions(self):
        data = self.cleaned_data.get("security_questions")
        # Optionally, add custom validation for the structure of each question-answer pair
        # e.g. ensure it's a list of dicts with keys: "question", "answer"
        if data:
            if not isinstance(data, list):
                raise ValidationError("Security questions must be a list.")
            for item in data:
                if not isinstance(item, dict):
                    raise ValidationError(
                        "Each security question must be a dictionary."
                    )
                if "question" not in item or "answer" not in item:
                    raise ValidationError(
                        "Each security question must have 'question' and 'answer'."
                    )
        return data

dashboard/templates/auth_base.html
{% load static %}
<!doctype html>
<html lang="en">
  <!-- [Head] start -->
  <head>
    <title></title>
    <!-- [Meta] -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="description"
      content="Berry is trending dashboard template made using Bootstrap 5 design framework. Berry is available in Bootstrap, React, CodeIgniter, Angular,  and .net Technologies."
    />
    <meta
      name="keywords"
      content="Bootstrap admin template, Dashboard UI Kit, Dashboard Template, Backend Panel, react dashboard, angular dashboard"
    />
    <meta name="author" content="codedthemes" />

    <!-- [Favicon] icon -->
    <link rel="icon" href="{% static 'images/favicon.svg' %}" type="image/x-icon" />
 <!-- [Google Font] Family -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" id="main-font-link" />
<!-- [phosphor Icons] https://phosphoricons.com/ -->
<link rel="stylesheet" href="{% static 'fonts/phosphor/duotone/style.css' %}" />
<!-- [Tabler Icons] https://tablericons.com -->
<link rel="stylesheet" href="{% static 'fonts/tabler-icons.min.css' %}" />
<!-- [Feather Icons] https://feathericons.com -->
<link rel="stylesheet" href="{% static 'fonts/feather.css' %}" />
<!-- [Font Awesome Icons] https://fontawesome.com/icons -->
<link rel="stylesheet" href="{% static 'fonts/fontawesome.css' %}" />
<!-- [Material Icons] https://fonts.google.com/icons -->
<link rel="stylesheet" href="{% static 'fonts/material.css' %}" />
<!-- [Template CSS Files] -->
<link rel="stylesheet" href="{% static 'css/style.css' %}" id="main-style-link" />
<link rel="stylesheet" href="{% static 'css/style-preset.css' %}" />

  </head>
  <!-- [Head] end -->
  <!-- [Body] Start -->
  <body>
    <!-- [ Pre-loader ] start -->
    <div class="loader-bg">
      <div class="loader-track">
        <!-- <div class="loader-fill"></div> -->
      </div>
    </div>
    <!-- [ Pre-loader ] End -->

    <div class="auth-main">
      <div class="auth-wrapper v3">
          <div class="auth-form">
              <div class="card">
                    <div class="card-body">
                        <a href="#" class="d-flex justify-content-center"
                          >
                                  <img style="height: 60px;" src="https://www.consolidated-bank.com/images/consolidated_bank_logo.png" alt="" srcset="">

                      </a>
                      <div class="py-2 px-4">
                          {% if messages %}
                          {% for message in messages %}
                          <div class="alert {% if message.tags == 'error' %} alert-danger {% else %} alert-success {% endif %} alert-dismissible show fade">
                              {{ message }}
                          </div>
                          {% endfor %}
                          {% endif %}
                      </div>

                      {% block content %}


                      {% endblock %}
                    </div>
              </div>
          </div>
      </div>
    </div>
    <!-- [ Main Content ] end -->
    <!-- Required Js -->
    <script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'js/plugins/popper.min.js' %}"></script>
    <script src="{% static 'js/plugins/simplebar.min.js' %}"></script>
    <script src="{% static 'js/plugins/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/icon/custom-font.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/theme.js' %}"></script>
    <script src="{% static 'js/plugins/feather.min.js' %}"></script>


    <script>
      layout_change('light');
    </script>

    <script>
      font_change('Roboto');
    </script>

    <script>
      change_box_container('false');
    </script>

    <script>
      layout_caption_change('true');
    </script>

    <script>
      layout_rtl_change('false');
    </script>

    <script>
      preset_change('preset-1');
    </script>


        <script>
        $(document).ready(function () {
          console.log("=== this function is runnign");
          $(".alert-success")
            .fadeTo(2000, 500)
            .slideUp(500, function () {
              $(".alert-success").slideUp(500);
            });
          $(".alert-danger")
            .fadeTo(2000, 500)
            .slideUp(500, function () {
              $(".alert-danger").slideUp(500);
            });
        });
      </script>

  </body>
  <!-- [Body] end -->
</html>

dashboard/templates/core_base.html
{% load static %}
<!doctype html>
<html lang="en">
  <!-- [Head] start -->
  <head>
    <title>Dashboard</title>
    <!-- [Meta] -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="description"
      content="Berry is trending dashboard template made using Bootstrap 5 design framework. Berry is available in Bootstrap, React, CodeIgniter, Angular,  and .net Technologies."
    />
    <meta
      name="keywords"
      content="Bootstrap admin template, Dashboard UI Kit, Dashboard Template, Backend Panel, react dashboard, angular dashboard"
    />
    <meta name="author" content="codedthemes" />

    <!-- [Favicon] icon -->
    <!-- <link rel="icon" href="{% static 'images/favicon.svg' %}" type="image/x-icon" /> -->
    <!-- [Google Font] Family -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" id="main-font-link" />
    <!-- [phosphor Icons] https://phosphoricons.com/ -->
    <link rel="stylesheet" href="{% static 'fonts/phosphor/duotone/style.css' %}" />
    <!-- [Tabler Icons] https://tablericons.com -->
    <link rel="stylesheet" href="{% static 'fonts/tabler-icons.min.css' %}" />
    <!-- [Feather Icons] https://feathericons.com -->
    <link rel="stylesheet" href="{% static 'fonts/feather.css' %}" />
    <!-- [Font Awesome Icons] https://fontawesome.com/icons -->
    <link rel="stylesheet" href="{% static 'fonts/fontawesome.css' %}" />
    <!-- [Material Icons] https://fonts.google.com/icons -->
    <link rel="stylesheet" href="{% static 'fonts/material.css' %}" />
    <!-- [Template CSS Files] -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" id="main-style-link" />
    <link rel="stylesheet" href="{% static 'css/style-preset.css' %}" />

  </head>
  <!-- [Head] end -->
  <!-- [Body] Start -->
  <body>
    <!-- [ Pre-loader ] start -->
<div class="loader-bg">
  <div class="loader-track">
    <div class="loader-fill"></div>
  </div>
</div>
<!-- [ Pre-loader ] End -->
    {% include "sidebar.html" %}
    {% include "header.html" %}



    <!-- [ Main Content ] start -->
    <div class="pc-container">
      <div class="pc-content p-3">
         <div>
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert {% if message.tags == 'error' %} alert-danger {% else %} alert-success {% endif %} alert-dismissible show fade">
                        {{ message }}
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>
        <!-- [ Main Content ] start -->
        {% block content %}

        {% endblock content %}
        <!-- [ Main Content ] end -->
      </div>
    </div>
    <!-- [ Main Content ] end -->
    {% include 'footer.html' %}

<script>
    // document.addEventListener('contextmenu', function(e) {
    //     e.preventDefault();
    // }, false);
</script>

 <!-- Required Js -->
<script src="{% static 'js/plugins/popper.min.js' %}"></script>
<script src="{% static 'js/plugins/simplebar.min.js' %}"></script>
<script src="{% static 'js/plugins/bootstrap.min.js' %}"></script>
<script src="{% static 'js/icon/custom-font.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script src="{% static 'js/theme.js' %}"></script>
<script src="{% static 'js/plugins/feather.min.js' %}"></script>


<script>
  layout_change('light');
</script>

<script>
  font_change('Roboto');
</script>

<script>
  change_box_container('false');
</script>

<script>
  layout_caption_change('true');
</script>

<script>
  layout_rtl_change('false');
</script>

<script>
  preset_change('preset-1');
</script>



    <!-- [Page Specific JS] start -->
    <!-- Apex Chart -->
    <script src="{% static 'js/plugins/apexcharts.min.js' %}"></script>
    <script src="{% static 'js/pages/dashboard-default.js' %}"></script>
    <!-- [Page Specific JS] end -->

     <script>
        $(document).ready(function () {
          console.log("=== this function is runnign");
          $(".alert-success")
            .fadeTo(2000, 500)
            .slideUp(500, function () {
              $(".alert-success").slideUp(500);
            });
          $(".alert-danger")
            .fadeTo(2000, 500)
            .slideUp(500, function () {
              $(".alert-danger").slideUp(500);
            });
        });
      </script>
  </body>
  <!-- [Body] end -->
</html>

dashboard/templates/footer.html
<footer class="pc-footer">
      <div class="footer-wrapper container-fluid">
        <div class="row">
          <div class="col-sm-6 my-1">
            <p class="m-0">
              Inlaks Limited
              <a href="" target="_blank"></a>
            </p>
          </div>
          <div class="col-sm-6 ms-auto my-1">

          </div>
        </div>
      </div>
</footer>

dashboard/templates/sidebar.html
{% load static %}
<!-- [ Sidebar Menu ] start -->
<nav class="pc-sidebar">
  <div class="navbar-wrapper">
    <div class="m-headers text-center p-4" >
      <a href="/" class="b-brand text-primary">
        <!-- ========   Change your logo from here   ============ -->
        <!-- <img src="{% static 'images/logo-dark.svg' %}" alt="" class="logo logo-lg" /> -->
        <img style="height: 40px;" class="logo " src="https://www.consolidated-bank.com/images/consolidated_bank_logo.png" alt="" srcset="">

      </a>
    </div>
    <div class="navbar-content">
      <ul class="pc-navbar">
        <!-- <li class="pc-item pc-caption">
          <label>Dashboard</label>
          <i class="ti ti-dashboard"></i>
        </li> -->
        <li class="pc-item">
          <a href="/" class="pc-link"
            ><span class="pc-micon"><i class="ti ti-user"></i></span><span class="pc-mtext">Dashboard</span></a
          >
        </li>

        <li class="pc-item pc-caption">
          <label>CORE</label>
          <i class="ti ti-apps"></i>
        </li>

        {% url 'dashboard:customers' as customers_url %}
        <li class="pc-item {% if request.path == quotations_url %}active{% endif %}">
          <a href="{{ customers_url }}" class="pc-link">
            <span class="pc-micon"><i class="ti ti-user"></i></span>
            <span class="pc-mtext">Customers</span>
          </a>
        </li>


        {% url 'dashboard:customer-requests' as customer_requests_url %}
        <li class="pc-item {% if request.path == quotations_url %}active{% endif %}">
          <a href="{{ customer_requests_url }}" class="pc-link">
            <span class="pc-micon"><i class="ti ti-arrows-double-sw-ne"></i></span>
            <span class="pc-mtext">Customers Requests</span>
          </a>
        </li>

        {% url 'dashboard:transfers' as transfers_url %}
        <li class="pc-item {% if request.path == quotations_url %}active{% endif %}">
          <a href="{{ transfers_url }}" class="pc-link">
            <span class="pc-micon"><i class="ti ti-transaction"></i></span>
            <span class="pc-mtext">Transactions</span>
          </a>
        </li>


        {% url 'dashboard:payments' as payments_url %}
        <li class="pc-item {% if request.path == payments_url %}active{% endif %}">
          <a href="{{ payments_url }}" class="pc-link">
            <span class="pc-micon"><i class="ti ti-credit-card-pay"></i></span>
            <span class="pc-mtext">Payments</span>
          </a>
        </li>

        <li class="pc-item">
          <a href="#" class="pc-link">
            <span class="pc-micon"><i class="ti ti-chart-scatter"></i></span>
            <span class="pc-mtext">Reports</span>
          </a>
        </li>


      </ul>

      <div class="w-100 text-center">
        <div class="badge theme-version badge rounded-pill bg-light text-dark f-12"></div>
      </div>
    </div>
  </div>
</nav>
<!-- [ Sidebar Menu ] end -->